server:
  port: 9000
  servlet:
    context-path: ${APP_PATH}
spring:
  datasource:
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 10
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}